### PR TITLE
Logic layer config file aliasing and docs

### PR DESCRIPTION
**Pull request by MarcioPorto**
Example config:

```json
{
    "aliases": {
        "cubes": [
            {
                "name": "example",
                "cube": "Example"
            }
        ]
    }
}
```

### CODE REVIEW

**Comment by hwchen** [comment]
Just want to check: this allows multiple aliases per cube?

**Comment by MarcioPorto** [comment]
Not currently... I'll add that.

**Comment by MarcioPorto** [comment]
@hwchen new example:

```json
{
    "aliases": {
        "cubes": [
            {
                "name": "Example",
                "alternatives": ["ex1", "ex2"]
            }
        ]
    }
}
```

**Comment by hwchen** [comment]
looks good, thanks!

**Pull request merged**
